export default [
  {
    date: "2018-04-21",
    records: [
      { selection: { start: 0, end: 0 }, interval: 0 },
      { selection: { start: 0, end: 0 }, interval: 800, to: "y" },
      { selection: { start: 1, end: 1 }, interval: 164, to: "i" },
      { selection: { start: 2, end: 2 }, interval: 152, to: "h" },
      { selection: { start: 3, end: 3 }, interval: 160, to: "o" },
      { selection: { start: 4, end: 4 }, interval: 96, to: "u" },
      { selection: { start: 0, end: 5 }, interval: 55, to: "以后" },
      { selection: { start: 2, end: 2 }, interval: 601, to: "b" },
      { selection: { start: 3, end: 3 }, interval: 47, to: "a" },
      { selection: { start: 4, end: 4 }, interval: 106, to: "b" },
      { selection: { start: 5, end: 5 }, interval: 103, to: "a" },
      { selection: { start: 2, end: 6 }, interval: 431, to: "爸爸" },
      { selection: { start: 4, end: 4 }, interval: 241, to: "m" },
      { selection: { start: 5, end: 5 }, interval: 122, to: "a" },
      { selection: { start: 6, end: 6 }, interval: 79, to: "m" },
      { selection: { start: 7, end: 7 }, interval: 103, to: "a" },
      { selection: { start: 4, end: 8 }, interval: 240, to: "妈妈" },
      { selection: { start: 6, end: 6 }, interval: 200, to: "j" },
      { selection: { start: 7, end: 7 }, interval: 79, to: "i" },
      { selection: { start: 8, end: 8 }, interval: 153, to: "u" },
      { selection: { start: 6, end: 9 }, interval: 72, to: "就" },
      { selection: { start: 7, end: 7 }, interval: 296, to: "k" },
      { selection: { start: 8, end: 8 }, interval: 103, to: "e" },
      { selection: { start: 9, end: 9 }, interval: 137, to: "y" },
      { selection: { start: 10, end: 10 }, interval: 177, to: "i" },
      { selection: { start: 7, end: 11 }, interval: 86, to: "可以" },
      { selection: { start: 9, end: 9 }, interval: 195, to: "z" },
      { selection: { start: 10, end: 10 }, interval: 199, to: "a" },
      { selection: { start: 11, end: 11 }, interval: 103, to: "i" },
      { selection: { start: 9, end: 12 }, interval: 114, to: "在" },
      { selection: { start: 10, end: 10 }, interval: 128, to: "z" },
      { selection: { start: 11, end: 11 }, interval: 127, to: "h" },
      { selection: { start: 12, end: 12 }, interval: 104, to: "e" },
      { selection: { start: 13, end: 13 }, interval: 134, to: "l" },
      { selection: { start: 14, end: 14 }, interval: 209, to: "i" },
      { selection: { start: 10, end: 15 }, interval: 81, to: "这里" },
      { selection: { start: 12, end: 12 }, interval: 1593, to: "j" },
      { selection: { start: 13, end: 13 }, interval: 77, to: "i" },
      { selection: { start: 14, end: 14 }, interval: 224, to: "l" },
      { selection: { start: 15, end: 15 }, interval: 202, to: "u" },
      { selection: { start: 12, end: 16 }, interval: 407, to: "记录" },
      { selection: { start: 14, end: 14 }, interval: 264, to: "n" },
      { selection: { start: 15, end: 15 }, interval: 95, to: "i" },
      { selection: { start: 14, end: 16 }, interval: 56, to: "你" },
      { selection: { start: 15, end: 15 }, interval: 275, to: "d" },
      { selection: { start: 16, end: 16 }, interval: 85, to: "e" },
      { selection: { start: 15, end: 17 }, interval: 64, to: "的" },
      { selection: { start: 16, end: 16 }, interval: 195, to: "c" },
      { selection: { start: 17, end: 17 }, interval: 96, to: "h" },
      { selection: { start: 18, end: 18 }, interval: 86, to: "e" },
      { selection: { start: 19, end: 19 }, interval: 104, to: "n" },
      { selection: { start: 20, end: 20 }, interval: 73, to: "g" },
      { selection: { start: 21, end: 21 }, interval: 215, to: "z" },
      { selection: { start: 22, end: 22 }, interval: 139, to: "h" },
      { selection: { start: 23, end: 23 }, interval: 357, to: "a" },
      { selection: { start: 24, end: 24 }, interval: 112, to: "n" },
      { selection: { start: 25, end: 25 }, interval: 111, to: "g" },
      { selection: { start: 16, end: 26 }, interval: 91, to: "成长" },
      { selection: { start: 18, end: 18 }, interval: 806, to: "g" },
      { selection: { start: 19, end: 19 }, interval: 104, to: "u" },
      { selection: { start: 20, end: 20 }, interval: 176, to: "s" },
      { selection: { start: 21, end: 21 }, interval: 88, to: "h" },
      { selection: { start: 22, end: 22 }, interval: 89, to: "i" },
      { selection: { start: 18, end: 23 }, interval: 678, to: "故事" },
      { selection: { start: 20, end: 20 }, interval: 194, to: "l" },
      { selection: { start: 21, end: 21 }, interval: 103, to: "a" },
      { selection: { start: 20, end: 22 }, interval: 496, to: "啦" }
    ]
  }
];
